#!/usr/bin/env python3
"""fix-ebs-vehicle-stragglers.py — Fifty-second-wave EBS-exhaustion straggler sweep.

Repairs the generic-vehicle ST bullets the seventh/eighth-pass corpus sweeps' exact-literal
guards could not see (different wordings of the same dodge classes): maintenance work-order
vehicles that ride Oracle eAM (F5), CAPA → Oracle Quality (C12), demand forecasting →
Demantra (C5), treasury → XTR/CE (A8), IC → AGIS (A7), vendor contracts → Procurement
Contracts (B12), masters → Product Hub/SLM (C1/B6), leases → Property Manager/A12 EXT (F3),
applicant tracking → iRecruitment (E2), markdown → Advanced Pricing, margin analytics →
In-Memory Cost (C15), dedup → TCA DQM/SLM (B6), training → OLA (E2), ERP-payroll posture
conflicts → Payroll PH (E5), route optimization → the in-house Route Optimization Engine and
load planning → in-suite OTE (C14), fleet maintenance → eAM (F5), registration-date alerting
→ Oracle Alert (G9).

Every replacement asserts its old fragment occurs EXACTLY once in its file (the wave-9
suite-caught-its-author precedent). Adjudicated-legitimate mentions are NOT touched and are
listed in the report: plain-word EBS module naming ('ERP Inventory module', 'Fixed Asset
module', 'ERP Tax Module', 'Pricing engine', 'ERP HR module'), domain-label cross-references
('HRIS (links to VS-29.2)'), build-posture naming (loyalty/gift-card/OMO/PIM/WFM/space-plan,
'Payroll module (W10)'), W544/W138 service-work-order cross-references, the W1225/W1308
customer-side contract rows, the W1315(W18) 3PL-fleet row and W2976's document-taxonomy dedup.
"""
import os, sys, re

# 2026-09-17 fifty-fourth-wave consistency review — repo-relative resolution per the
# eighteenth-wave shipped-tooling portability repair (the authored '/home/alden'
# absolute path was unrunnable on any other checkout).
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WF = os.path.join(ROOT, "01-model-company", "workflows")

FIXES = [
    # --- eAM (fit-gap F5): maintenance / facility work-order vehicles ---
    ("VS-04-dc-warehouse/PA-04.3-dc-operations-management.md",
     "- Work order system for corrective maintenance",
     "- Oracle eAM corrective-maintenance work orders (fit-gap F5)"),
    ("VS-04-dc-warehouse/PA-04.3-dc-operations-management.md",
     "- Maintenance work order system (W650) for HVAC and sensor maintenance",
     "- Oracle eAM maintenance work orders (W650) for HVAC and sensor maintenance (fit-gap F5)"),
    ("VS-07-store-operations/PA-07.1-store-daily-management.md",
     "- Maintenance work order system (W47) — failed inspection corrective actions",
     "- Oracle eAM maintenance work orders (W47) — failed inspection corrective actions (fit-gap F5)"),
    ("VS-07-store-operations/PA-07.1-store-daily-management.md",
     "- Maintenance work order system (W47) — equipment repair requests",
     "- Oracle eAM maintenance work orders (W47) — equipment repair requests (fit-gap F5)"),
    ("VS-07-store-operations/PA-07.2-store-facility-and-safety.md",
     "- Equipment maintenance request system (W48, W47)",
     "- Oracle eAM work requests (W48, W47 — fit-gap F5)"),
    ("VS-07-store-operations/PA-07.2-store-facility-and-safety.md",
     "- Monthly PM scheduling system with task lists per equipment type",
     "- Oracle eAM PM scheduling with task lists per equipment type (fit-gap F5)"),
    ("VS-07-store-operations/PA-07.2-store-facility-and-safety.md",
     "- Maintenance work order system (W47) for repair tracking",
     "- Oracle eAM maintenance work orders (W47) for repair tracking (fit-gap F5)"),
    ("VS-07-store-operations/PA-07.2-store-facility-and-safety.md",
     "- Maintenance work order system (W47) for exterior repairs",
     "- Oracle eAM maintenance work orders (W47) for exterior repairs (fit-gap F5)"),
    ("VS-07-store-operations/PA-07.2-store-facility-and-safety.md",
     "- Maintenance work order system (W47) — canopy repair, drainage cleaning",
     "- Oracle eAM maintenance work orders (W47) — canopy repair, drainage cleaning (fit-gap F5)"),
    ("VS-07-store-operations/PA-07.2-store-facility-and-safety.md",
     "- Facility maintenance work order module (W47) — tarp replacement",
     "- Oracle eAM facility work orders (W47) — tarp replacement (fit-gap F5)"),
    ("VS-07-store-operations/PA-07.2-store-facility-and-safety.md",
     "- Facility maintenance work order system (W47) — equipment repair",
     "- Oracle eAM facility work orders (W47) — equipment repair (fit-gap F5)"),
    ("VS-07-store-operations/PA-07.3-store-receiving-and-replenishment.md",
     "- Maintenance work order system for repair tracking",
     "- Oracle eAM maintenance work orders for repair tracking (fit-gap F5)"),
    ("VS-24-health-safety-environment/PA-24.2-emergency-preparedness.md",
     "- Work order system for deficiency remediation per W47",
     "- Oracle eAM work orders for deficiency remediation per W47 (fit-gap F5)"),
    ("VS-24-health-safety-environment/PA-24.2-emergency-preparedness.md",
     "- Facilities maintenance work order system for generator preventive maintenance",
     "- Oracle eAM work orders for generator preventive maintenance (fit-gap F5)"),
    ("VS-26-business-continuity-insurance/PA-26.2-crisis-response-and-recovery.md",
     "- Facility maintenance work order system per W47",
     "- Oracle eAM facility work orders per W47 (fit-gap F5)"),
    ("VS-35-fixed-asset-management/PA-35.1-asset-registration-lifecycle.md",
     "- Maintenance work order module with cost tracking (W1695.2–3)",
     "- Oracle eAM work orders with cost tracking (W1695.2–3 — fit-gap F5)"),
    ("VS-12-installation-services/PA-12.2-tool-rental-and-equipment.md",
     "- PM work order system with completion logging and findings documentation (W1554.2)",
     "- Oracle eAM PM work orders with completion logging and findings documentation (W1554.2 — fit-gap F5)"),
    ("VS-20-real-estate-construction/PA-20.2-engineering-and-construction.md",
     "- Work Order module for renovation project tracking and task assignment",
     "- Oracle Projects renovation cost capture/CIP; task scheduling stays PMO tooling (coverage-map Engineering & Construction row)"),
    # --- Oracle Quality (fit-gap C12): CAPA / supplier-quality vehicles ---
    ("VS-03-vendor-management/PA-03.1-vendor-sourcing-and-onboarding.md",
     "- CAPA tracking integration (W110) for factory corrective actions following audit findings",
     "- Oracle Quality CAPA tracking (W110) for factory corrective actions following audit findings (fit-gap C12)"),
    ("VS-03-vendor-management/PA-03.3-vendor-performance-and-contracts.md",
     "- Vendor improvement plan tracking (W110, CAPA module)",
     "- Vendor improvement plan tracking (W110 — Oracle Quality CAPA, fit-gap C12)"),
    ("VS-04-dc-warehouse/PA-04.1-dc-inbound-operations.md",
     "- CAPA module (W110)",
     "- Oracle Quality CAPA (W110 — fit-gap C12)"),
    ("VS-07-store-operations/PA-07.1-store-daily-management.md",
     "- Vendor quality CAPA module (W110) — vendor escalation",
     "- Oracle Quality vendor CAPA (W110) — vendor escalation (fit-gap C12)"),
    ("VS-07-store-operations/PA-07.2-store-facility-and-safety.md",
     "- Vendor quality CAPA system (W110)",
     "- Oracle Quality vendor CAPA (W110 — fit-gap C12)"),
    ("VS-09-in-store-services/PA-09.2-project-estimation-and-advisory.md",
     "- Supplier quality management system (W110)",
     "- Oracle Quality supplier quality (W110 — fit-gap C12)"),
    ("VS-25-esg-sustainability/PA-25.2-social-impact-and-governance.md",
     "- CAPA tracking and vendor de-listing workflow (W36.12)",
     "- Oracle Quality CAPA tracking and vendor de-listing workflow (W36.12 — fit-gap C12)"),
    # --- Demantra (fit-gap C5): demand forecasting vehicles ---
    ("VS-03-vendor-management/PA-03.4-vendor-portal-and-collaboration.md",
     "- Demand planning / forecasting module (W31) — seasonal indices, historical data",
     "- Demantra demand planning/forecasting (W31) — seasonal indices, historical data (fit-gap C5)"),
    ("VS-09-in-store-services/PA-09.1-custom-fabrication-and-processing.md",
     "- Demand forecasting module (W31) with seasonal modeling",
     "- Demantra demand forecasting (W31) with seasonal modeling (fit-gap C5)"),
    ("VS-28-data-analytics-bi/PA-28.3-advanced-analytics.md",
     "- **ERP Forecasting Module** — baseline statistical forecast (W31) for comparison",
     "- **Demantra statistical forecasting** (fit-gap C5) — baseline statistical forecast (W31) for comparison"),
    ("VS-29-master-data/PA-29.3-extended-masters.md",
     "- Demand Forecasting Engine (W31 — event-driven forecast adjustment)",
     "- Demantra demand forecasting (W31 — event-driven forecast adjustment — fit-gap C5)"),
    # --- Oracle Treasury (fit-gap A8): cash forecasting / treasury vehicles ---
    ("VS-18-treasury-cash/PA-18.1-cash-positioning-and-forecasting.md",
     "- Cash Flow Forecasting tool (direct/indirect methods, 13-week rolling forecast)",
     "- Oracle Treasury (XTR) cash-flow forecasting (fit-gap A8 — direct/indirect methods, 13-week rolling forecast)"),
    ("VS-18-treasury-cash/PA-18.1-cash-positioning-and-forecasting.md",
     "- Cash flow forecasting module",
     "- Oracle Treasury (XTR) cash-flow forecasting (fit-gap A8)"),
    ("VS-03-vendor-management/PA-03.1-vendor-sourcing-and-onboarding.md",
     "- Treasury management system — cash position, bank balances",
     "- Oracle Treasury (XTR)/CE — cash position, bank balances (fit-gap A8)"),
    ("VS-18-treasury-cash/PA-18.2-banking-and-payments.md",
     "- Treasury management system with LC tracking (W1294.3)",
     "- Oracle Treasury (XTR) with LC tracking (W1294.3 — fit-gap A8)"),
    # --- AGIS (fit-gap A7): intercompany vehicles ---
    ("VS-11-trade-project-wholesale/PA-11.2-project-sales-and-b2b.md",
     "- Intercompany module (W14) — cross-entity settlement if needed",
     "- AGIS intercompany (W14) — cross-entity settlement if needed (fit-gap A7)"),
    ("VS-17-record-to-report/PA-17.2-consolidation-and-intercompany.md",
     "- ERP Intercompany module: IC pricing rules, auto-invoice generation, IC settlement",
     "- AGIS: IC pricing rules, auto-invoice generation, IC settlement (fit-gap A7)"),
    ("VS-19-hire-to-retire/PA-19.3-workforce-management.md",
     "- Finance intercompany module per W87 for cost allocations",
     "- AGIS intercompany per W87 for cost allocations (fit-gap A7)"),
    ("VS-20-real-estate-construction/PA-20.1-site-selection-and-lease-management.md",
     "- Intercompany module per W87 for Property Management entity leases",
     "- AGIS intercompany per W87 for Property Management entity leases (fit-gap A7)"),
    ("VS-29-master-data/PA-29.2-financial-and-operational-masters.md",
     "- ERP Intercompany Module (IC pricing rule engine)",
     "- AGIS (IC pricing rule engine — fit-gap A7)"),
    ("VS-29-master-data/PA-29.2-financial-and-operational-masters.md",
     "- Intercompany Module (IC period alignment — W14)",
     "- AGIS (IC period alignment — W14 — fit-gap A7)"),
    ("VS-79-tax-management-bir-reporting/PA-79.2-withholding-tax-and-2307-management.md",
     "- ERP AP final-tax code; treasury intercompany module; BIR eFPS 1601F",
     "- ERP AP final-tax code; AGIS intercompany (fit-gap A7); BIR eFPS 1601F"),
    # --- Procurement Contracts (fit-gap B12): vendor contract vehicles ---
    ("VS-06-logistics-fleet/PA-06.3-last-mile-and-delivery-partners.md",
     "- Contract management module — rate tables, SLA terms, renewal dates (W1439.5)",
     "- Oracle Procurement Contracts — rate tables, SLA terms, renewal dates (W1439.5 — fit-gap B12)"),
    ("VS-09-in-store-services/PA-09.1-custom-fabrication-and-processing.md",
     "- Contract management module (W402) — FPA document storage, expiry tracking",
     "- Oracle Procurement Contracts (W402) — FPA document storage, expiry tracking (fit-gap B12)"),
    ("VS-17-record-to-report/PA-17.2-consolidation-and-intercompany.md",
     "- Contract management module: service agreement lifecycle tracking with renewal dates",
     "- Oracle Procurement Contracts: service agreement lifecycle tracking with renewal dates (fit-gap B12)"),
    # --- Masters: Product Hub / SLM (fit-gap C1/B6) ---
    ("VS-29-master-data/PA-29.1-foundational-masters.md",
     "- ERP Item Master Module (centralized creation, attribute fields)",
     "- Oracle Product Hub (centralized item creation, attribute fields — fit-gap C1)"),
    ("VS-29-master-data/PA-29.1-foundational-masters.md",
     "- ERP Vendor Master Module",
     "- Oracle SLM vendor master (fit-gap B6)"),
    ("VS-29-master-data/PA-29.2-financial-and-operational-masters.md",
     "- ERP UOM Master / Item Master Module",
     "- INV UOM master / Oracle Product Hub item master (fit-gap C1/C2)"),
    ("VS-29-master-data/PA-29.3-extended-masters.md",
     "- ERP Item Master Module (barcode fields per SKU)",
     "- Oracle Product Hub item master (barcode fields per SKU — fit-gap C1)"),
    ("VS-29-master-data/PA-29.3-extended-masters.md",
     "- ERP Item Master Module (lifecycle status field per SKU)",
     "- Oracle Product Hub item master (lifecycle status field per SKU — fit-gap C1)"),
    ("VS-09-in-store-services/PA-09.1-custom-fabrication-and-processing.md",
     "- Item master module — lumber species, grade, and target moisture range",
     "- Oracle Product Hub item master — lumber species, grade, and target moisture range (fit-gap C1)"),
    # --- Property Manager (fit-gap F3) / A12 EXT ROU schedules ---
    ("VS-20-real-estate-construction/PA-20.1-site-selection-and-lease-management.md",
     "- Lease management system — lease expiration tracker, terms database, renewal status (W1446.1)",
     "- Oracle Property Manager — lease expiration tracker, terms database, renewal status (W1446.1 — fit-gap F3)"),
    ("VS-20-real-estate-construction/PA-20.1-site-selection-and-lease-management.md",
     "- Lease Administration Module",
     "- Oracle Property Manager lease administration (fit-gap F3); ROU schedules per the A12 EXT (GL/FA)"),
    ("VS-29-master-data/PA-29.1-foundational-masters.md",
     "- IFRS 16 Lease Accounting Module",
     "- GL/FA ROU schedules (the A12 EXT)"),
    ("VS-35-fixed-asset-management/PA-35.1-asset-registration-lifecycle.md",
     "- PFRS 16 lease accounting module: right-of-use asset and lease liability management (W1696.3)",
     "- GL/FA ROU schedules (the A12 EXT): right-of-use asset and lease liability management (W1696.3)"),
    ("VS-42-property-lease-admin/PA-42.1-lease-negotiation-administration.md",
     "- PFRS 16 sublease accounting module (W1860.4b)",
     "- GL/FA ROU sublease schedules (the A12 EXT — W1860.4b)"),
    ("VS-15-procure-to-pay/PA-15.2-vendor-payment-and-reconciliation.md",
     "- Lease accounting module (IFRS 16), GL, AP (lease payments), intercompany module (IC leases), consolidation module",
     "- GL/FA ROU schedules (the A12 EXT), GL, AP (lease payments), AGIS (IC leases — fit-gap A7), GL consolidation"),
    # --- iRecruitment (fit-gap E2): applicant-tracking vehicles ---
    ("VS-19-hire-to-retire/PA-19.1-recruitment-and-onboarding.md",
     "- Applicant tracking module",
     "- Oracle iRecruitment applicant tracking (fit-gap E2)"),
    ("VS-19-hire-to-retire/PA-19.1-recruitment-and-onboarding.md",
     "- Applicant tracking system linked to recruitment pipeline per W15",
     "- Oracle iRecruitment linked to recruitment pipeline per W15 (fit-gap E2)"),
    # --- Advanced Pricing: markdown vehicles ---
    ("VS-05-inventory-lifecycle/PA-05.3-inventory-disposition-and-optimization.md",
     "- Progressive markdown engine — scheduled markdown phases with automatic POS price update (W1438.3)",
     "- Advanced Pricing progressive markdown schedule — scheduled markdown phases with automatic POS price update (W1438.3)"),
    ("VS-07-store-operations/PA-07.2-store-facility-and-safety.md",
     "- Markdown module (W93) — progressive markdown automation",
     "- Advanced Pricing markdown (W93) — progressive markdown automation"),
    ("VS-09-in-store-services/PA-09.1-custom-fabrication-and-processing.md",
     "- Markdown module (W93) — near-expiry pricing automation",
     "- Advanced Pricing markdown (W93) — near-expiry pricing automation"),
    ("VS-09-in-store-services/PA-09.1-custom-fabrication-and-processing.md",
     "- Pricing/markdown module — moisture-based reclassification pricing",
     "- Advanced Pricing — moisture-based reclassification pricing"),
    # --- In-Memory Cost Management (fit-gap C15): margin analytics ---
    ("VS-03-vendor-management/PA-03.1-vendor-sourcing-and-onboarding.md",
     "- Margin analysis module",
     "- In-Memory Cost Management margin analytics (fit-gap C15)"),
    ("VS-03-vendor-management/PA-03.3-vendor-performance-and-contracts.md",
     "- Margin analysis module (W85) — pre/post recall margin comparison",
     "- In-Memory Cost Management margin analytics (W85) — pre/post recall margin comparison (fit-gap C15)"),
    ("VS-10-ecommerce-digital/PA-10.2-order-fulfillment-and-delivery.md",
     "- Fulfillment cost allocation and margin analysis module (W1195.6)",
     "- Fulfillment cost allocation and In-Memory Cost margin analytics (W1195.6 — fit-gap C15)"),
    # --- TCA DQM / SLM (fit-gap B6): master dedup vehicles ---
    ("VS-13-customer-experience/PA-13.2-loyalty-program-operations.md",
     "- Deduplication engine (W253) with real-time matching",
     "- TCA DQM deduplication (W253) with real-time matching (fit-gap B6)"),
    ("VS-29-master-data/PA-29.1-foundational-masters.md",
     "- Customer Data Platform (CDP) deduplication engine",
     "- TCA DQM deduplication (fit-gap B6) — engagement identities stay on the in-house CDP"),
    ("VS-29-master-data/PA-29.1-foundational-masters.md",
     "- Deduplication Engine",
     "- Oracle SLM duplicate check (fit-gap B6)"),
    # --- Oracle Learning Management (fit-gap E2): training vehicles ---
    ("VS-09-in-store-services/PA-09.1-custom-fabrication-and-processing.md",
     "- Training management module linked to HR system (W51) for training history",
     "- Oracle Learning Management linked to HR system (W51) for training history (fit-gap E2)"),
    ("VS-24-health-safety-environment/PA-24.1-occupational-health-and-safety.md",
     "- Training management module, employee master (W292), certification database, scheduling module, compliance reporting",
     "- Oracle Learning Management (fit-gap E2), employee master (W292), certification database, scheduling module, compliance reporting"),
    ("VS-20-real-estate-construction/PA-20.2-engineering-and-construction.md",
     "- HR onboarding and training management system with certification tracking (W1295.3)",
     "- HR onboarding and Oracle Learning Management training/certification tracking (W1295.3 — fit-gap E2)"),
    # --- Payroll posture conflicts → Payroll PH build (fit-gap E5) ---
    ("VS-07-store-operations/PA-07.4-store-staffing-and-people.md",
     "- ERP HR/Payroll module: hours worked, overtime, premium calculations, budget allocation",
     "- Payroll PH (in-house build — fit-gap E5): hours worked, overtime, premium calculations, budget allocation"),
    ("VS-15-procure-to-pay/PA-15.2-vendor-payment-and-reconciliation.md",
     "- ERP Payroll module: hours accumulation, rate calculation, accrual generation",
     "- Payroll PH (in-house build — fit-gap E5): hours accumulation, rate calculation, accrual generation"),
    # --- Route Optimization Engine / OTE (fit-gap C14) ---
    ("VS-02-supply-planning/PA-02.3-supply-chain-orchestration-and-risk.md",
     "- Route optimization engine — multi-stop route planning with constraints",
     "- Route Optimization Engine (in-house build — fit-gap C14) — multi-stop route planning with constraints"),
    ("VS-04-dc-warehouse/PA-04.1-dc-inbound-operations.md",
     "- Route planning module — outbound delivery route assignment and manifest generation",
     "- Route Optimization Engine (in-house build — fit-gap C14) — outbound delivery route assignment and manifest generation"),
    ("VS-04-dc-warehouse/PA-04.2-dc-outbound-operations.md",
     "- Route optimization engine: multi-stop routing with traffic, time window, and cost optimization (W106.2)",
     "- Route Optimization Engine (in-house build — fit-gap C14): multi-stop routing with traffic, time window, and cost optimization (W106.2)"),
    ("VS-04-dc-warehouse/PA-04.2-dc-outbound-operations.md",
     "- Automated multi-stop route optimization engine with geographic proximity grouping, stop sequencing, vehicle type assignment, and ferry schedule alignment (W1369.3)",
     "- Automated multi-stop Route Optimization Engine (in-house build — fit-gap C14) with geographic proximity grouping, stop sequencing, vehicle type assignment, and ferry schedule alignment (W1369.3)"),
    ("VS-06-logistics-fleet/PA-06.1-outbound-distribution.md",
     "- Route planning module (W15) — delivery route optimization with stop sequencing",
     "- Route Optimization Engine (in-house build — fit-gap C14) — delivery route optimization with stop sequencing"),
    ("VS-06-logistics-fleet/PA-06.1-outbound-distribution.md",
     "- Load planning module — weight calculation, vehicle capacity matching, load sequence generation",
     "- Shipping/Transportation Execution load planning (in-suite — fit-gap C14) — weight calculation, vehicle capacity matching, load sequence generation"),
    ("VS-06-logistics-fleet/PA-06.3-last-mile-and-delivery-partners.md",
     "- Route optimization engine (W196)",
     "- Route Optimization Engine (W196 — in-house build, fit-gap C14)"),
    ("VS-06-logistics-fleet/PA-06.3-last-mile-and-delivery-partners.md",
     "- Route optimization engine — fuel efficiency simulation and route redesign (W1440.4)",
     "- Route Optimization Engine (in-house build — fit-gap C14) — fuel efficiency simulation and route redesign (W1440.4)"),
    ("VS-09-in-store-services/PA-09.1-custom-fabrication-and-processing.md",
     "- Delivery scheduling and route planning module (W196) with LGU truck ban awareness (W431)",
     "- Delivery scheduling and Route Optimization Engine (W196, in-house build — fit-gap C14) with LGU truck ban awareness (W431)"),
    ("VS-11-trade-project-wholesale/PA-11.2-project-sales-and-b2b.md",
     "- Route optimization module (W196)",
     "- Route Optimization Engine (W196 — in-house build, fit-gap C14)"),
    ("VS-11-trade-project-wholesale/PA-11.2-project-sales-and-b2b.md",
     "- Delivery route optimization module for multi-drop scheduling",
     "- Route Optimization Engine multi-drop scheduling (in-house build — fit-gap C14)"),
    ("VS-04-dc-warehouse/PA-04.2-dc-outbound-operations.md",
     "- Load planning module: integrate cross-dock items with regular picked items per W106",
     "- Shipping/Transportation Execution load planning (in-suite — fit-gap C14): integrate cross-dock items with regular picked items per W106"),
    ("VS-180-disaster-relief-supply-chain-logistics-and-humanitarian-aid-coordination/PA-180.1-emergency-material-allocation-disaster-kit-assembly-staging-operations.md",
     "- Logistics control tower (W250), GPS tracking system, route optimization software.",
     "- Logistics control tower (W250), GPS tracking system, in-house Route Optimization Engine (fit-gap C14)."),
    # --- Fleet maintenance vehicle (fit-gap F5) ---
    ("VS-09-in-store-services/PA-09.1-custom-fabrication-and-processing.md",
     "- Fleet management module (W52, W199) — vehicle type availability, driver assignment",
     "- FA vehicle register + eAM maintenance holds (W52, W199 — fit-gap F5) — vehicle type availability; driver assignment in the in-house WFM build"),
    # --- Oracle Alert (fit-gap G9): registration-date alerting ---
    ("VS-22-compliance-regulatory/PA-22.2-government-audit-and-inspection-response.md",
     "- Calendar/alert system for registration expiry tracking",
     "- Oracle Alert (ALR) date alerting over the registration EIT register (fit-gap G9)"),
]

applied, skipped = [], []
for rel, old, new in FIXES:
    path = os.path.join(WF, rel)
    txt = open(path, encoding="utf-8").read()
    n = txt.count(old)
    if n != 1:
        skipped.append((rel, old[:70], f"count={n}"))
        continue
    open(path, "w", encoding="utf-8").write(txt.replace(old, new))
    applied.append((rel, old[:70]))

print(f"APPLIED {len(applied)}/{len(FIXES)}")
for rel, frag, why in skipped:
    print(f"SKIPPED|{rel}|{why}|{frag}")
